CREATE TABLE tb_negara(
   id_negara   VARCHAR(2) NOT NULL PRIMARY KEY
  ,nama_negara VARCHAR(44) NOT NULL
);
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CN','China');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('FM','Micronesia, Federated States Of');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GL','Greenland');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CU','Cuba');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CI','Cote D''Ivoire');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BA','Bosnia And Herzegovina');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GH','Ghana');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BD','Bangladesh');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GI','Gibraltar');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('EE','Estonia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CL','Chile');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CF','Central African Republic');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BY','Belarus');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AI','Anguilla');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BO','Bolivia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('DO','Dominican Republic');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('ES','Spain');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BB','Barbados');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CM','Cameroon');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BW','Botswana');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AE','United Arab Emirates');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CR','Costa Rica');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AT','Austria');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AG','Antigua And Barbuda');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BI','Burundi');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AS','American Samoa');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('DZ','Algeria');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GA','Gabon');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AR','Argentina');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GF','French Guiana');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('EG','Egypt');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('ET','Ethiopia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CK','Cook Islands');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('HK','Hong Kong');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('DE','Germany');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BT','Bhutan');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BS','Bahamas');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GM','Gambia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BR','Brazil');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CG','Congo');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('DJ','Djibouti');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CA','Canada');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('HM','Heard Island And Mcdonald Islands');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('DM','Dominica');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AQ','Antarctica');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BG','Bulgaria');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('FO','Faroe Islands');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AF','Afghanistan');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('ER','Eritrea');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GW','Guinea-Bissau');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BE','Belgium');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('EC','Ecuador');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AW','Aruba');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AU','Australia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BJ','Benin');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BH','Bahrain');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CZ','Czech Republic');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('FR','France');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GY','Guyana');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GU','Guam');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GN','Guinea');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BZ','Belize');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AZ','Azerbaijan');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BN','Brunei Darussalam');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BM','Bermuda');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('FJ','Fiji');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CO','Colombia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GG','Guernsey');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AL','Albania');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CY','Cyprus');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AX','Aland Islands');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GE','Georgia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AM','Armenia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GB','United Kingdom');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('FI','Finland');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GD','Grenada');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CX','Christmas Island');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CH','Switzerland');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('DK','Denmark');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BV','Bouvet Island');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AO','Angola');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('NI','Nicaragua');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MD','Moldova, Republic Of');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('KI','Kiribati');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('KY','Cayman Islands');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('LT','Lithuania');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MG','Madagascar');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MQ','Martinique');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('HN','Honduras');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('LR','Liberia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('PT','Portugal');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('PY','Paraguay');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MH','Marshall Islands');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('PW','Palau');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('PK','Pakistan');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('PM','Saint Pierre And Miquelon');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('JO','Jordan');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('NP','Nepal');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MK','Macedonia, The Former Yugoslav Republic Of');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('LI','Liechtenstein');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('ID','Indonesia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('KR','Korea, Republic Of');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GS','South Georgia And The South Sandwich Islands');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('HT','Haiti');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('IE','Ireland');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('RE','Reunion');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MP','Northern Mariana Islands');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MN','Mongolia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('NZ','New Zealand');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MW','Malawi');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('PR','Puerto Rico');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('IN','India');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('NE','Niger');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('NF','Norfolk Island');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GT','Guatemala');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('NU','Niue');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('NG','Nigeria');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('KM','Comoros');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('LC','Saint Lucia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('IQ','Iraq');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('KE','Kenya');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MX','Mexico');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MV','Maldives');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('PN','Pitcairn');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MR','Mauritania');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('KZ','Kazakhstan');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('LU','Luxembourg');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('KH','Cambodia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('LK','Sri Lanka');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('PL','Poland');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('LV','Latvia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('LS','Lesotho');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MA','Morocco');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('JM','Jamaica');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('LA','Lao People''S Democratic Republic');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MU','Mauritius');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MZ','Mozambique');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MO','Macao');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('OM','Oman');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('NO','Norway');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('IM','Isle Of Man');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('KW','Kuwait');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('NR','Nauru');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MY','Malaysia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('LB','Lebanon');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MM','Myanmar');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GR','Greece');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('IT','Italy');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('IS','Iceland');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('HU','Hungary');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('ML','Mali');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('JP','Japan');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('IL','Israel');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MS','Montserrat');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('NA','Namibia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('JE','Jersey');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('KN','Saint Kitts And Nevis');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('QA','Qatar');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('HR','Croatia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MT','Malta');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('KG','Kyrgyzstan');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CS','Serbia And Montenegro');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('PA','Panama');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('ZM','Zambia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('PE','Peru');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('ZW','Zimbabwe');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('ST','Sao Tome And Principe');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('IO','British Indian Ocean Territory');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('RW','Rwanda');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SD','Sudan');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SY','Syrian Arab Republic');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('TC','Turks And Caicos Islands');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('VE','Venezuela');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('TL','Timor-Leste');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('PG','Papua New Guinea');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('NL','Netherlands');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SZ','Swaziland');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('VU','Vanuatu');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('EH','Western Sahara');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CW','Curacao');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SR','Suriname');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('UA','Ukraine');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('TM','Turkmenistan');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AD','Andorra');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SA','Saudi Arabia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('TN','Tunisia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('TK','Tokelau');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SC','Seychelles');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('TH','Thailand');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('VA','Holy See (Vatican City State)');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MF','Saint Martin');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('WS','Samoa');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('UM','United States Minor Outlying Islands');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('ME','Montenegro');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SX','Sint Maarten');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('VG','Virgin Islands, British');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SK','Slovakia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GP','Guadeloupe');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('YT','Mayotte');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SO','Somalia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('VC','Saint Vincent And The Grenadines');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('TZ','Tanzania, United Republic Of');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('LY','Libyan Arab Jamahiriya');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SG','Singapore');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SM','San Marino');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('YE','Yemen');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('UY','Uruguay');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('UZ','Uzbekistan');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SJ','Svalbard And Jan Mayen');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SL','Sierra Leone');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SV','El Salvador');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SE','Sweden');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('TV','Tuvalu');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CD','Congo, The Democratic Republic Of The');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('UG','Uganda');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('TD','Chad');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('RS','Serbia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('TJ','Tajikistan');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('TW','Taiwan, Province Of China');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SS','South Sudan');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('PF','French Polynesia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('VN','Viet Nam');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('VI','Virgin Islands, U.S.');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BQ','Bonaire, Saint Eustatius and Saba');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SI','Slovenia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('RU','Russian Federation');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('TO','Tonga');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('WF','Wallis And Futuna');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CC','Cocos (Keeling) Islands');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('ZA','South Africa');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('RO','Romania');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('TT','Trinidad And Tobago');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SH','Saint Helena');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('TR','Turkey');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SB','Solomon Islands');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('SN','Senegal');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('US','United States');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('PH','Philippines');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('TG','Togo');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('MC','Monaco');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('NC','New Caledonia');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BF','Burkina Faso');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('BL','Saint Bartelemey');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('KP','Korea, Democratic People''S Republic Of');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('CV','Cape Verde');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('PS','Palestinian Territory, Occupied');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('AN','Netherlands Antilles');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('GQ','Equatorial Guinea');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('FK','Falkland Islands (Malvinas)');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('IR','Iran, Islamic Republic Of');
INSERT INTO tb_negara(id_negara,nama_negara) VALUES ('TF','French Southern Territories');
